#Read below property from Config Server
#eureka:
#   client:
#      serviceUrl:
#         defaultZone: http://localhost:8761/eureka
 
spring:
  config:
    import: optional:configserver:http://localhost:9191      