server:
 port: 9090
 
 
spring:
 application:
  name: gateway-app
 cloud:
  gateway:
   routes:
    - id: orderClient
      uri: lb://ORDER-SERVICE
      predicates:
       - Path=/orders
    - id: inventoryClient
      uri: lb://INVENTORY-SERVICE
      predicates:
       - Path=/inventory 
    - id: cardClient
      uri: lb://CREDITCARD-SERVICE
      predicates:
       - Path=/cards/**
#Read below property from Config Server
#eureka:
#   client:
#      serviceUrl:
#         defaultZone: http://localhost:8761/eureka
 config:
  import: optional:configserver:http://localhost:9191